# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a36799c1c4426228757707dea448cafb48ef7be078243444c9fb640c15dda552f223cf88ae34846fbeb1cc2ccd7b57b6250b55b22926a2c97ef1a14778ec0262

test:
  secret_key_base: 3ac9a0e6feae133316fccecd2de53497e9af0d3a3b72365e6550cbb02b2a660d8e80e861b07f8a1b7ef7a4d3457d4ac09b94cde59b41f2717bdd7a0d7f044b0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
